In [131]:
import pandas as pd
import numpy as np


In [133]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [134]:
pd.__version__

'2.2.2'

In [135]:
len(df)

9704

In [139]:
df.head()


,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [141]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [143]:
df.isnull()
df


,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551


In [145]:
df.fuel_efficiency_mpg.max()


25.96722204888372

In [147]:
maxima_eficiencia_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
print(f"La máxima eficiencia de los autos provenientes de Asia es: {maxima_eficiencia_asia} millas por galón.")

La máxima eficiencia de los autos provenientes de Asia es: 23.759122836520497 millas por galón.


In [149]:
df.horsepower.mean()

149.65729212983547

In [151]:
df.horsepower.count()

8996

In [153]:
df.origin.count()

9704

In [155]:
frecuencia_maxima = df['horsepower'].value_counts().max()
print(f"Se repite un total de: {frecuencia_maxima} veces")


Se repite un total de: 142 veces


In [157]:
valor_mas_repetido = df['horsepower'].value_counts().idxmax()
print(f"El número que más se repite en la columna 'horsepower' es: {valor_mas_repetido}")

El número que más se repite en la columna 'horsepower' es: 152.0


In [159]:
# 1. Usar .isnull() para obtener un booleano para cada celda (True si es nulo)
# 2. Usar .sum() para sumar esos True's por columna
# 3. Filtrar el resultado para mostrar solo las columnas cuya suma sea mayor a 0

columnas_con_nulos = df.isnull().sum()
columnas_con_nulos = columnas_con_nulos[columnas_con_nulos > 0]

print("Columnas con valores faltantes y su conteo:")
print(columnas_con_nulos)

Columnas con valores faltantes y su conteo:
num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64


In [161]:
# 1. Define la media que has calculado
media_horsepower = 149.6572

# 2. Usa fillna() para reemplazar los valores nulos en la columna 'horsepower'
#    Usamos inplace=True para modificar el DataFrame original directamente
df['horsepower'].fillna(149.6572)

0       159.0000
1        97.0000
2        78.0000
3       149.6572
4       140.0000
          ...   
9699    164.0000
9700    154.0000
9701    138.0000
9702    177.0000
9703    140.0000
Name: horsepower, Length: 9704, dtype: float64

In [163]:
df.horsepower.mean()

149.65729212983547

In [165]:
df['origin']

0       Europe
1          USA
2       Europe
3          USA
4       Europe
         ...  
9699    Europe
9700       USA
9701       USA
9702       USA
9703      Asia
Name: origin, Length: 9704, dtype: object

In [167]:
df_asia = df[df['origin'] == 'Asia']

In [169]:
print(df_asia)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [171]:
df_filtrado = df[['vehicle_weight', 'model_year']]
print(df_filtrado)

      vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]


In [173]:
df_asia_select = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
print(df_asia_select)


    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [175]:
X = df_asia_select.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [177]:
XTX = X.T.dot(X)
print("\nMatriz XTX:")
print(XTX)


Matriz XTX:
[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]


In [179]:
XTX_inv = np.linalg.inv(XTX)
print("Inversa de XTX:")
print(XTX_inv)

Inversa de XTX:
[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]


In [181]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array(y)
print(y)

[1100 1300  800  900 1000 1100 1200]


In [183]:
w = XTX_inv.dot(X.T).dot(y)
print(w)

[0.01386421 0.5049067 ]


In [185]:
suma_elem_w = np.sum(w)
print(suma_elem_w)


0.5187709081074026
